// Package models defines the domain models for the UGC application.
package models

import (
	"time"

	"github.com/google/uuid"
)

// JobStatus constants represent the possible states of a job.
const (
	StatusPending         = "pending"
	StatusAnalyzing       = "analyzing"
	StatusGeneratingMusic = "generating_music"
	StatusSelectingSong   = "selecting_song"
	StatusGeneratingImage = "generating_image"
	StatusProcessingVideo = "processing_video"
	StatusUploading        = "uploading"
	StatusUploadingYouTube = "uploading_youtube"
	StatusCompleted        = "completed"
	StatusFailed           = "failed"
)

// SongPrompt represents the output from Agent 1 (music prompt generation).
type SongPrompt struct {
	Prompt       string `json:"prompt"`
	Style        string `json:"style"`
	Title        string `json:"title"`
	TitleEn      string `json:"title_en"`
	Model        string `json:"model"`
	Instrumental bool   `json:"instrumental"`
}

// GeneratedSong represents a song generated by the music service (Suno).
type GeneratedSong struct {
	ID       string  `json:"id"`
	AudioURL string  `json:"audio_url"`
	Title    string  `json:"title"`
	Duration float64 `json:"duration"`
}

// ImagePrompt represents the prompt for image generation.
type ImagePrompt struct {
	Prompt    string `json:"prompt"`
	ImageSize string `json:"image_size"`
}

// Job represents a UGC content generation job.
type Job struct {
	ID             uuid.UUID       `json:"id" db:"id"`
	UserID         uuid.UUID       `json:"user_id" db:"user_id"`
	Status         string          `json:"status" db:"status"`
	Concept        string          `json:"concept" db:"concept"`
	LLMModel       string          `json:"llm_model" db:"llm_model"`
	SongPrompt     *SongPrompt     `json:"song_prompt,omitempty" db:"song_prompt"`
	SunoTaskID     *string         `json:"suno_task_id,omitempty" db:"suno_task_id"`
	GeneratedSongs []GeneratedSong `json:"generated_songs,omitempty" db:"generated_songs"`
	SelectedSongID *string         `json:"selected_song_id,omitempty" db:"selected_song_id"`
	ImagePrompt    *ImagePrompt    `json:"image_prompt,omitempty" db:"image_prompt"`
	NanoTaskID     *string         `json:"nano_task_id,omitempty" db:"nano_task_id"`
	AudioURL       *string         `json:"audio_url,omitempty" db:"audio_url"`
	ImageURL       *string         `json:"image_url,omitempty" db:"image_url"`
	VideoURL       *string         `json:"video_url,omitempty" db:"video_url"`
	YouTubeURL     *string         `json:"youtube_url,omitempty" db:"youtube_url"`
	YouTubeVideoID *string         `json:"youtube_video_id,omitempty" db:"youtube_video_id"`
	YouTubeError   *string         `json:"youtube_error,omitempty" db:"youtube_error"`
	ErrorMessage   *string         `json:"error_message,omitempty" db:"error_message"`
	CreatedAt      time.Time       `json:"created_at" db:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at" db:"updated_at"`
}

// CreateJobInput represents the input for creating a new job.
type CreateJobInput struct {
	Concept string  `json:"concept" validate:"required,min=5"`
	Model   *string `json:"model,omitempty"`
}

// JobResponse represents the API response for a job.
type JobResponse struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	Status         string          `json:"status"`
	Concept        string          `json:"concept"`
	LLMModel       string          `json:"llm_model"`
	SongPrompt     *SongPrompt     `json:"song_prompt,omitempty"`
	GeneratedSongs []GeneratedSong `json:"generated_songs,omitempty"`
	SelectedSongID *string         `json:"selected_song_id,omitempty"`
	ImagePrompt    *ImagePrompt    `json:"image_prompt,omitempty"`
	AudioURL       *string         `json:"audio_url,omitempty"`
	ImageURL       *string         `json:"image_url,omitempty"`
	VideoURL       *string         `json:"video_url,omitempty"`
	YouTubeURL     *string         `json:"youtube_url,omitempty"`
	YouTubeVideoID *string         `json:"youtube_video_id,omitempty"`
	YouTubeError   *string         `json:"youtube_error,omitempty"`
	ErrorMessage   *string         `json:"error_message,omitempty"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

// ToResponse converts a Job to a JobResponse.
// This method filters out internal fields that should not be exposed in the API.
func (j *Job) ToResponse() *JobResponse {
	return &JobResponse{
		ID:             j.ID,
		UserID:         j.UserID,
		Status:         j.Status,
		Concept:        j.Concept,
		LLMModel:       j.LLMModel,
		SongPrompt:     j.SongPrompt,
		GeneratedSongs: j.GeneratedSongs,
		SelectedSongID: j.SelectedSongID,
		ImagePrompt:    j.ImagePrompt,
		AudioURL:       j.AudioURL,
		ImageURL:       j.ImageURL,
		VideoURL:       j.VideoURL,
		YouTubeURL:     j.YouTubeURL,
		YouTubeVideoID: j.YouTubeVideoID,
		YouTubeError:   j.YouTubeError,
		ErrorMessage:   j.ErrorMessage,
		CreatedAt:      j.CreatedAt,
		UpdatedAt:      j.UpdatedAt,
	}
}

// IsTerminal returns true if the job is in a terminal state (completed or failed).
func (j *Job) IsTerminal() bool {
	return j.Status == StatusCompleted || j.Status == StatusFailed
}

// CanRetry returns true if the job can be retried (only failed jobs can be retried).
func (j *Job) CanRetry() bool {
	return j.Status == StatusFailed
}
